# This Cloud Build configuration file automates the deployment of the
# custom HAPI FHIR server to Cloud Run.

steps:
  # Step 1: Build the custom Docker image.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args:
      - 'build'
      - '--tag'
      - '${_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REGISTRY_REPOSITORY}/${_SERVICE_NAME}'
      - '.'

  # Step 2: Push the Docker image to Google Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    waitFor: ['docker-build']
    args:
      - 'push'
      - '${_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REGISTRY_REPOSITORY}/${_SERVICE_NAME}'

  # Step 3: Deploy the new image to Cloud Run.
  # This step takes the image we just pushed and deploys it as a new revision
  # of our Cloud Run service, applying all necessary configurations.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'gcloud-run-deploy'
    waitFor: ['docker-push']
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REGISTRY_REPOSITORY}/${_SERVICE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - --vpc-connector
      - $_VPC_CONNECTOR
      - --vpc-egress
      - all-traffic
      - --service-account
      - $_SERVICE_ACCOUNT
      # -- Secrets Configuration --
      # -- HAPI FHIR Specific Settings --
      - '--port=8080'
      - '--memory=4Gi'
      - '--cpu=4000m'
      - '--timeout=900s' # Increase timeout for a large application
      # -- Cloud SQL Connection --
      # The service account needs "Cloud SQL Client" role.
      - '--add-cloudsql-instances=${_INSTANCE_CONNECTION_NAME}'
      # -- Environment Variables --
      - '--set-env-vars=SPRING_DATASOURCE_URL=${_SPRING_DATASOURCE_URL}'
      - '--set-env-vars=SPRING_DATASOURCE_USERNAME=${_SPRING_DATASOURCE_USERNAME}'
      - '--set-env-vars=SPRING_DATASOURCE_PASSWORD=${_SPRING_DATASOURCE_PASSWORD}'
      - '--set-env-vars=SPRING_DATASOURCE_DRIVERCLASSNAME=${_SPRING_DATASOURCE_DRIVERCLASSNAME}'

# This specifies which image was built, allowing it to be seen in the build summary.
images:
  - '${_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REGISTRY_REPOSITORY}/${_SERVICE_NAME}'

# Default timeout for the entire build.
timeout: '1200s'

# Define substitution variables that can be set when you trigger the build.
substitutions:
  _REGISTRY_LOCATION: 'southamerica-east1'
  _REGISTRY_REPOSITORY: 'docker'
  _REGION: 'southamerica-west1'
  _SERVICE_NAME: 'hapi-fhir-server'
  _INSTANCE_CONNECTION_NAME: 'ceroai:southamerica-west1:integracion-rayen-avis'
  _SPRING_DATASOURCE_DRIVERCLASSNAME: 'org.postgresql.Driver'
  _VPC_CONNECTOR: vpc-connector-rayen